name: Addon

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code check
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm install

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Build
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: npm run pack:ff

      - name: XPI 
        env:
          FTP_HOST: ${{ secrets.HOST }}
          FTP_USER: ${{ secrets.USER }}
          FTP_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          lftp -u "$FTP_USER","$FTP_PASSWORD" $FTP_HOST <<EOF
  
