name: Addon

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: npm install
        working-directory: /addon-todo-activité1
        run: npm install

      - name: lftp install
        run: sudo apt-get install -y lftp

      - name: build
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: npm run pack:ff

      - name: xpi setup 
        env:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
        run: |
          lftp -u "$user","$password" $host <<EOF
  
